FROM python:3.11-slim


WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt


COPY app ./app


ENV DOCS_DIR=/app/app/data
ENV HOST=0.0.0.0
ENV PORT=8000


EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]